routes/web.php
<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['as' => 'admin.', 'name' => 'admin.', 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::resource('article', 'ArticleController');
    Route::resource('movie', 'MovieController');
    Route::resource('show', 'ShowController');
    Route::resource('type', 'TypeController');
    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

declare(strict_types=1);

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;

final class Category extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'title',
        'is_active',
    ];

    protected $casts = [
        'is_active' => 'bool',
    ];

    public function articles(): BelongsToMany
    {
        return $this->belongsToMany(Article::class, 'article_categories');
    }

    public static function determineCategoriesForArticle(array $categories): array
    {
        $result = [];

        foreach ($categories as $category) {
            $result[] = self::firstOrCreate(['title' => $category])->id;
        }

        return $result;
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use Illuminate\Http\RedirectResponse as RedirectResponseAlias;
use Illuminate\Http\Request;
use Illuminate\View\View;

final class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $view = view('admin.category.index');
        $view->categories = Category::latest()->take(50)->get();

        return $view;
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreCategoryRequest $request): RedirectResponseAlias
    {
        $title = $request->get('title');

        $category = Category::create([
            'title' => $title,
            'is_active' => 1,
        ]);

        return redirect()->action(
            'Admin\CategoryController@show',
            ['category' => $category]
        );
    }

    /**
     * Display the specified resource.
     */
    public function show(Category $category): View
    {
        $view = view('admin.category.show');
        $view->category = $category;

        return $view;
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Category $category): View
    {
        $view = view('admin.category.edit');
        $view->category = $category;

        return $view;
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateCategoryRequest $request, Category $category): RedirectResponseAlias
    {
        $active = $request->get('is_active') !== null && $request->get('is_active') === 1;

        $category->title = $request->get('title');
        $category->is_active = $active;

        $category->save();

        return redirect()->action(
            'Admin\CategoryController@show',
            ['category' => $category]
        );
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Category $category): RedirectResponseAlias
    {
        $category->is_active = false;
        $category->save();

        $category->delete();

        return redirect()->action('Admin\CategoryController@index');
    }

    /**
     * @return array[]
     */
    public function search(Request $request): array
    {
        $search = $request->query('s');

        $categories = Category::where(['title' => $search, 'is_active' => true])->take(10)->get();

        $result = [];

        foreach ($categories as $category) {
            $result[] = [
                'id' => $category->id,
                'title' => $category->title,
            ];
        }

        return [
            'data' => $result,
        ];
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.base')

@section('content')
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h5>Toevoegen categorie</h5>
            </div>
            <div class="card-body">
                {!! Form::open(['route' => ['admin.category.store'], 'method' => 'POST', 'id' => 'sa-new-article']) !!}
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group row">
                                <div class="col-sm-12">
                                    {!! Form::text('title', null, ['id' => 'articleTitle', 'class' => 'form-control', 'placeholder' => 'Naam van de categorie']) !!}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group row">
                                <div class="col-sm-12">
                                    {!! Form::submit('Opslaan', ['class' => 'btn btn-primary']) !!}
                                </div>
                            </div>
                        </div>
                    </div>
                    @if ($errors->any())
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            </div>
                        </div>
                    @endif
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

@section('extra-css')
    <!-- multi-select css -->
    <link rel="stylesheet" href="/vendor/backend/plugins/multi-select/css/multi-select.css">
    <link rel="stylesheet" href="/vendor/backend/plugins/material-datetimepicker/css/bootstrap-material-datetimepicker.css">
    <!-- Bootstrap datetimepicker css -->
    <link rel="stylesheet" href="/vendor/backend/plugins/bootstrap-datetimepicker/css/bootstrap-datepicker3.min.css">
    <link rel="stylesheet" href="/vendor/backend/fonts/material/css/materialdesignicons.min.css">
    <!-- minicolors css -->
    <link rel="stylesheet" href="/vendor/backend/plugins/mini-color/css/jquery.minicolors.css">
    <!-- multi-select css -->
    <link rel="stylesheet" href="/vendor/backend/plugins/multi-select/css/multi-select.css">

    <!-- bootstrap-tagsinput-latest css -->
    <link rel="stylesheet" href="/vendor/backend/plugins/bootstrap-tagsinput-latest/css/bootstrap-tagsinput.css">

    <link rel="stylesheet" href="/vendor/backend/css/style.css">
@endsection

@section('extra-js')
    <script src="https://momentjs.com/downloads/moment-with-locales.min.js"></script>
    <script src="/vendor/backend/plugins/material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>

    <!-- minicolors Js -->
    <script src="/vendor/backend/plugins/mini-color/js/jquery.minicolors.min.js"></script>

    <!-- multi-select Js -->
    <script src="/vendor/backend/plugins/multi-select/js/jquery.quicksearch.js"></script>
    <script src="/vendor/backend/plugins/multi-select/js/jquery.multi-select.js"></script>

    <!-- TinyMCE -->
    <script src="/js/tinymce/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="/js/tinymce/langs/nl.js" referrerpolicy="origin"></script>

    <script>
        tinymce.init({
            selector: '#articleContent',
            plugins: [
                'autoresize advlist autolink link image lists charmap preview hr anchor pagebreak spellchecker',
                'searchreplace visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
                'table emoticons paste help'
            ],
            toolbar: 'undo redo | styleselect | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify |' +
                ' bullist numlist outdent indent | link image media | print preview fullpage | ' +
                'forecolor backcolor emoticons | help',
            menubar: 'file edit view insert format tools table help',
            content_css: 'css/content.css',
            lang: 'nl',
            spellchecker_language: 'nl',
            width: '100%',
        });
    </script>

    <script type="text/javascript">
        $('.date-format').bootstrapMaterialDatePicker({
            format: 'Y-M-D HH:mm',
            minDate: new Date(),
            lang: 'nl'
        });
    </script>

    <script src="/js/backend/article/select2.category.js"></script>
    <script src="/js/backend/article/select2.movies.js"></script>
    <script src="/js/backend/article/select2.shows.js"></script>
    <script src="/js/backend/article/select2.types.js"></script>
    <script src="/js/backend/article/select2.tags.js"></script>

@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.base')

@section('content')
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h5>Bewerken categorie</h5><small>{{ $category->title }}</small>
            </div>
            {{ Form::open(['action' => ['Admin\CategoryController@update', $category->id], 'method' => 'PATCH']) }}
                <div class="col-12">
                    <div class="form-group row m-t-20">
                        <label for="categoryTitle" class="col-1 col-form-label">Naam</label>
                        <div class="col-11">
                            {!! Form::text('title', $category->title, ['id' => 'categoryTitle', 'class' => 'form-control', 'placeholder' => 'Naam van het artikel']) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-1 col-form-label">Actief?</label>
                        <div class="col-11">
                            Nee
                            <div class="col-10 switch switch-success d-inline m-r-10">
                                <input name="is_active" value="1" type="checkbox" id="switch-s-1" @if ($category->is_active) checked @endif>
                                <label for="switch-s-1" class="cr"></label>
                            </div>
                            Ja
                        </div>
                    </div>
                    @if ($errors->any())
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            </div>
                        </div>
                    @endif
                    <div class="form-group row">
                        <div class="offset-1 col-11">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Reset</button>
                            <a class="btn btn-warning" href="{{ route('admin.category.index') }}">Annuleren</a>
                            <button type="submit" class="btn btn-success">Opslaan</button>
                        </div>
                    </div>
                </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('extra-css')

@endsection

@section('extra-js')


@endsection

resources/views/admin/category/index.blade.php
@extends('admin.base')
@section('content')
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h5>Categories</h5>
                <hr>
                <table id="footable-table" class="table table-striped table-hover footable footable-1 footable-paging footable-paging-center breakpoint-lg" style="">
                    <thead>
                    <tr class="footable-header">
                        <th class="footable-sortable footable-first-visible" >
                            Categorie
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th class="footable-sortable footable-first-visible" >
                            Actief?
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th class="footable-sortable footable-first-visible" >
                            # Artikelen
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th data-breakpoints="xs" class="footable-sortable" >
                            Aangemaakt op
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th class="footable-last-visible">
                            Opties
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($categories as $category)
                            <tr>
                                <td><a href="{{ route('admin.category.show', $category) }}">{{ $category->title }}</a></td>
                                <td>@if ($category->is_active) Ja @else Nee @endif </td>
                                <td>
                                    {{ $category->articles->count() }}
                                </td>
                                <td>
                                    {{ $category->created_at->format('d-m-Y H:i') }}
                                </td>
                                <td>
                                    <a href="{{ route('admin.category.edit', $category) }}" class="btn btn-primary">Bewerken</a>
                                    <a href="{{ route('admin.category.destroy', $category->id) }}" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-category="{{ $category->title }}">Verwijder</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel">Verwijderen categorie</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            </div>
                            <div class="modal-body">
                                Weet je zeker dat je deze categorie wilt verwijderen?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary">Annuleren</button>
                                {{ Form::open(['method' => 'DELETE', 'id' => 'deleteCategoryForm']) }}
                                    <button type="submit" class="btn btn-danger">Verwijderen</button>
                                {{ Form::close() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('extra-css')
    <!-- datatables css -->
    <link rel="stylesheet" href="/vendor/backend/plugins/data-tables/css/datatables.min.css">

    <!-- footable css -->
    <link rel="stylesheet" href="/vendor/backend/plugins/footable/css/footable.bootstrap.min.css">
    <link rel="stylesheet" href="/vendor/backend/plugins/footable/css/footable.standalone.min.css">
@endsection

@section('extra-js')
    <script src="/vendor/backend/plugins/footable/js/footable.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#footable-table').footable({
                "paging": {
                    "enabled": false,
                    "size": 50
                },
                "sorting": {
                    "enabled": true
                }
            });
        });
    </script>
    <script>
        $('#deleteModal').on('show.bs.modal', function(e) {
            let button = $(e.relatedTarget);
            let category = button.data('category');
            let modal = $(this);

            modal.find('.modal-title').text('Verwijderen categorie ' + category);
            modal.find('.modal-body').text('Weet je zeker dat je de categorie ' + category + ' wilt verwijderen?');
            modal.find('#deleteCategoryForm').attr('action', button.attr('href'));
        })
    </script>
@endsection

resources/views/admin/category/show.blade.php
@extends('admin.base')
@section('content')
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h5>Bekijk categorie "{{$category->title}}"</h5>
                <hr>
                <h6>Artikelen bij deze categorie</h6>
                <table id="footable-table" class="table table-striped table-hover footable footable-1 footable-paging footable-paging-center breakpoint-lg" style="">
                    <thead>
                    <tr class="footable-header">
                        <th class="footable-sortable footable-first-visible" >
                            Titel
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th data-breakpoints="xs" class="footable-sortable" >
                            Gepubliceerd (op)
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th data-breakpoints="xs" class="footable-sortable" >
                            Type
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th class="footable-last-visible">
                            Opties
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($category->articles as $article)
                        <tr>
                            <td><a href="{{ route('admin.article.show', $article) }}">{{ $article->title }}</a></td>
                            <td>
                                @if ($article->published)
                                    Ja
                                @else
                                    Nee
                                @endif
                                ({{ $article->published_at->format('Y-m-d H:i') }})</td>
                            <td>
                                <ul>
                                @foreach($article->types as $type)
                                    <li>{{ $type->type }}</li>
                                @endforeach
                                </ul>
                            </td>
                            <td>
                                <a href="{{ route('admin.article.show', $article) }}">Bekijken</a>
                                <a href="{{ route('admin.article.edit', $article) }}">Bewerken</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection