routes/web.php
<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['as' => 'admin.', 'name' => 'admin.', 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::resource('article', 'ArticleController');
    Route::resource('movie', 'MovieController');
    Route::resource('show', 'ShowController');
    Route::resource('type', 'TypeController');
    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

app/Movie.php
<?php

declare(strict_types=1);

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;

final class Movie extends Model
{
    use SoftDeletes;

    public const STATUSES = [
        'released',
        'in production',
        'post production',
        'planned',
        'rumored',
        'canceled',
    ];

    public $timestamps = true;

    protected $dates = [
        'released_at',
        'created_at',
        'updated_at',
    ];

    protected $casts = [
        'is_processed' => 'bool',
    ];

    protected $fillable = [
        'id_trakt',
        'title',
    ];

    public function genres(): BelongsToMany
    {
        return $this->belongsToMany(Genre::class, 'movie_genres');
    }

    public function articles(): BelongsToMany
    {
        return $this->belongsToMany(Article::class, 'article_movies');
    }
}

app/Http/Controllers/Admin/MovieController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreMovieRequest;
use App\Http\Requests\UpdateMovieRequest;
use App\Movie;
use App\Repositories\MovieRepository;
use App\Services\TraktApiService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

final class MovieController extends Controller
{
    public function __construct()
    {
        $this->movieRepository = new MovieRepository();
    }

    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $view = view('admin.movie.index');
        $view->movies = Movie::latest()->take(50)->get();

        return $view;
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        return view('admin.movie.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreMovieRequest $request): RedirectResponse
    {
        $traktMovieId = $request->get('trakt-movie-id');

        $movie = $this->movieRepository->createMovie($traktMovieId);

        return redirect()->action(
            'Admin\MovieController@show',
            ['movie' => $movie]
        );
    }

    /**
     * Display the specified resource.
     */
    public function show(Movie $movie): View
    {
        $view = view('admin.movie.show');
        $view->movie = $movie;

        return $view;
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Movie $movie): View
    {
        $view = view('admin.show.edit');
        $view->movie = $movie;

        return $view;
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateMovieRequest $request, Movie $movie): RedirectResponse
    {
        $movie->title = $request->get('title');
        $movie->tagline = $request->get('tagline');
        $movie->released_at = $request->get('released_at');
        $movie->status = $request->get('status');
        $movie->country = mb_strtoupper($request->get('country'));
        $movie->runtime = $request->get('runtime');
        $movie->trailer = $request->get('trailer');
        $movie->homepage = $request->get('homepage');
        $movie->overview_nl = $request->get('overview');
        $movie->save();

        return redirect()->action(
            'Admin\MovieController@show',
            ['movie' => $movie]
        );
    }

    /**
     * Search a movie using an API
     */
    public function search(Request $request): array
    {
        $search = $request->query('s');
        $result = TraktApiService::searchMovieForArticle($search);

        $results = [];

        foreach ($result as $movie) {
            $results[] = $movie->movie;
        }

        return $results;
    }
}

resources/views/admin/movie/create.blade.php
@extends('admin.base')

@section('content')
<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
            <h5>Toevoegen movie</h5>
        </div>
        <div class="card-body">
            {{ Form::open(['route' => ['admin.movie.store'], 'method' => 'POST', 'id' => 'sa-new-movie']) }}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <select name="trakt-movie-id" id="movie-name" class="col-sm-12 select2-hidden-accessible" tabindex="-1" aria-hidden="true"></select>
                    </div>
                </div>
                {!! Form::submit('Opslaan', ['class' => 'btn btn-primary']) !!}
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

@section('extra-css')
<!-- select2 css -->
<link rel="stylesheet" href="/vendor/backend/plugins/select2/css/select2.min.css">
<!-- multi-select css -->
<link rel="stylesheet" href="/vendor/backend/plugins/multi-select/css/multi-select.css">
@endsection

@section('extra-js')
<!-- select2 Js -->
<script src="/vendor/backend/plugins/select2/js/select2.full.min.js"></script>
<script src="/vendor/backend/plugins/select2/js/i18n/nl.js"></script>

<!-- multi-select Js -->
<script src="/vendor/backend/plugins/multi-select/js/jquery.quicksearch.js"></script>
<script src="/vendor/backend/plugins/multi-select/js/jquery.multi-select.js"></script>

<script type="text/javascript">
    $("#movie-name").select2({
        ajax: {
            method: "GET",
            url: "{{ route('api.admin.movie.search') }}",
            //dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    s: params.term, // search term
                };
            },
            processResults: function (data, params) {
                params.page = params.page || 1;

                return {
                    results: data.data,
                    pagination: {
                        more: (params.page * 30) < data.total_count
                    }
                };
            },
            cache: true
        },
        placeholder: 'Naam van de movie',
        minimumInputLength: 1,
        lang: 'nl',
        templateResult: formatMovie,
        templateSelection: formatMovieSelection
    });

    function formatMovie (movie) {
        if (!movie.year) {
            movie.year = 'onbekend';
        }

        var $container = $(
            '<div class="select2-result-movie clearfix">' +
                '<div class="select2-result-movie__title">' + movie.title + ' (' + movie.year + ')</div>' +
                '<div class="select2-result-movie__meta">' +
                    '<div class="select2-result-movie__tagline">' + movie.tagline + '</div>' +
                '</div>' +
            '</div>'
        );

        return $container;
    }

    function formatMovieSelection (movie) {
        return movie.title || movie.text;
    }
</script>
@endsection

resources/views/admin/movie/edit.blade.php
@extends('admin.base')

@section('content')
<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
            <h5>Film bewerken</h5>
        </div>
        <div class="card-body">
            <h5>{{ $movie->title }}</h5>
            <div class="row">
                <div class="col-md-6">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    {{ Form::open(['action' => ['Admin\MovieController@update', $movie->id], 'method' => 'PATCH']) }}
                        <div class="form-group row">
                            <label for="movieTitle" class="col-sm-3 col-form-label">Title</label>
                            <div class="col-sm-9">
                                {!! Form::text('title', $movie->title, ['id' => 'movieTitle', 'class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="movieTagline" class="col-sm-3 col-form-label">Tagline</label>
                            <div class="col-sm-9">
                                {!! Form::text('tagline', $movie->tagline, ['id' => 'movieTagline', 'class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="movieRelease" class="col-sm-3 col-form-label">Released (Y-m-d)</label>
                            <div class="col-sm-9">
                                {!! Form::text('released_at', $movie->released_at->format('Y-m-d'), ['id' => 'date', 'class' => 'form-control', 'placeholder' => 'Date']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="movieStatus" class="col-sm-3 col-form-label">Status</label>
                            <div class="col-sm-9">
                                {!! Form::select('status', App\Movie::STATUSES, $movie->status, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="movieCountry" class="col-sm-3 col-form-label">Country (production)</label>
                            <div class="col-sm-9">
                                {!! Form::select('country', App\Country::COUNTRIES, strtoupper($movie->country), ['class' => 'form-control js-example-basic-single select2-hidden-accessible', 'data-select2-id' => 1, 'tabindex' => '-1', 'aria-hidden' => 'true']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="movieRuntime" class="col-sm-3 col-form-label">Runtime (in minutes)</label>
                            <div class="col-sm-9">
                                {!! Form::number('runtime', $movie->runtime, ['id' => 'movieRuntime', 'class' => 'form-control', 'min' => 1, 'max' => 200]) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="movieTrailer" class="col-sm-3 col-form-label">
                                Trailer - <a href="{{ $movie->trailer }}" rel="nofollow" target="_blank">Watch it</a>
                            </label>
                            <div class="col-sm-9">
                                {!! Form::text('trailer', $movie->trailer, ['id' => 'movieTrailer', 'class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="movieHomepage" class="col-sm-3 col-form-label">Homepage</label>
                            <div class="col-sm-9">
                                {!! Form::text('homepage', $movie->homepage, ['id' => 'movieHomepage', 'class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="movieGenres" class="col-sm-3 col-form-label">Genres (comma separated)</label>
                            <div class="col-sm-9">
                                {!! Form::text('genres', implode(',', $movie->genres), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="movieOverviewEn" class="col-sm-3 col-form-label">Overview (English)</label>
                            <div class="col-sm-9">
                                {!! Form::textarea('overview_en', $movie->overview_en, ['id' => 'movieOverviewEn', 'class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="movieOverviewNl" class="col-sm-3 col-form-label">Overview (Dutch)</label>
                            <div class="col-sm-9">
                                {!! Form::textarea('overview_nl', $movie->overview_nl, ['id' => 'movieOverviewNl', 'class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">
                                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('extra-js')
<script src="https://momentjs.com/downloads/moment-with-locales.min.js"></script>
        <script src="/vendor/backend/plugins/material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
        <script src="/vendor/backend/plugins/select2/js/select2.full.min.js"></script>
        <script src="/vendor/backend/plugins/select2/js/i18n/nl.js"></script>
        <script src="/vendor/backend/plugins/multi-select/js/jquery.quicksearch.js"></script>
        <script src="/vendor/backend/plugins/multi-select/js/jquery.multi-select.js"></script>
        <script src="/vendor/backend/plugins/mini-color/js/jquery.minicolors.min.js"></script>
        <script src="/vendor/backend/js/pages/form-picker-custom.js"></script>
        <script src="/vendor/backend/plugins/bootstrap-tagsinput-latest/js/bootstrap-tagsinput.min.js"></script>
        <script src="/vendor/backend/js/pages/form-select-custom.js"></script>
@endsection

@section('extra-css')
<!-- material datetimepicker css -->
        <link rel="stylesheet" href="/vendor/backend/plugins/material-datetimepicker/css/bootstrap-material-datetimepicker.css">
        <link rel="stylesheet" href="/vendor/backend/plugins/bootstrap-datetimepicker/css/bootstrap-datepicker3.min.css">
        <link rel="stylesheet" href="/vendor/backend/fonts/material/css/materialdesignicons.min.css">
        <link rel="stylesheet" href="/vendor/backend/plugins/mini-color/css/jquery.minicolors.css">

        <link rel="stylesheet" href="/vendor/backend/plugins/select2/css/select2.min.css">
@endsection

resources/views/admin/movie/index.blade.php
@extends('admin.base')
@section('content')
<div class="col-sm-12">
    <div class="card">
        <div class="card-body">
            <h5>Movies</h5>
            <hr>
            <table id="footable-table" class="table table-striped table-hover footable footable-1 footable-paging footable-paging-center breakpoint-lg" style="">
                <thead>
                    <tr class="footable-header">
                        <th class="footable-sortable footable-first-visible" >
                            Titel
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th class="footable-sortable footable-first-visible" >
                            Ondertitel
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th data-breakpoints="xs" class="footable-sortable" >
                            Jaar
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th data-breakpoints="xs" class="footable-sortable" >
                            Speelduur
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th data-breakpoints="xs" class="footable-sortable" >
                            Status
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th data-breakpoints="xs" class="footable-sortable" >
                            Verwerkt?
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th class="footable-sortable footable-last-visible">
                            Datums
                        </th>
                        <th class="footable-last-visible">
                            Opties
                        </th>
                    </tr>
                </thead>
                <tbody>
                @foreach($movies as $movie)
                    <tr>
                        <td>
                            <a href="{{ route('admin.movie.show', $movie) }}">{{ $movie->title }}</a>
                        </td>
                        <td>{{ $movie->tagline }}</td>
                        <td>{{ $movie->released_at->year }}</td>
                        <td>{{ $movie->runtime }}m</td>
                        <td>{{ $movie->status }}</td>
                        <td>
                            @if ($movie->is_processed)
                                <i class="feather icon-check-square"></i>
                            @else
                                <i class="feather icon-square"></i>
                            @endif
                        </td>
                        <td>
                            Added: {{ $movie->created_at->format('d-m-Y H:i:s') }}
                            @if ($movie->created_at != $movie->updated_at)
                                <br>Updated: {{ $movie->updated_at->format('d-m-Y H:i:s') }}
                            @endif
                        </td>
                        <td>
                            <a href="{{ route('admin.movie.edit', $movie) }}">Bewerken</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@section('extra-css')
<!-- datatables css -->
<link rel="stylesheet" href="/vendor/backend/plugins/data-tables/css/datatables.min.css">

<!-- footable css -->
<link rel="stylesheet" href="/vendor/backend/plugins/footable/css/footable.bootstrap.min.css">
<link rel="stylesheet" href="/vendor/backend/plugins/footable/css/footable.standalone.min.css">
@endsection

@section('extra-js')
<script src="/vendor/backend/plugins/footable/js/footable.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#footable-table').footable({
            "paging": {
                "enabled": false,
                "size": 50
            },
            "sorting": {
                "enabled": true
            }
        });
    });
</script>
@endsection

resources/views/admin/movie/show.blade.php
@extends('admin.base')
@section('content')
<div class="col-xl-4 col-md-6">
    <div class="card user-card user-card-1">
        <div class="card-header border-0 p-2 pb-0">
            <div class="cover-img-block">
                <img src="/vendor/backend/images/widget/slider7.jpg" alt="" class="img-fluid">
            </div>
        </div>
        <div class="card-body pt-0">
            <div class="user-about-block text-center">
                <div class="row align-items-end">
                    <div class="col text-left pb-3"></div>
                    <div class="col"><img class="img-radius img-fluid wid-80" src="/vendor/backend/images/user/avatar-1.jpg" alt="User image"></div>
                    <div class="col text-right pb-3">
                        <div class="dropdown">
                            <a class="drp-icon dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="feather icon-more-horizontal"></i></a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="{{ route('admin.movie.edit', $movie) }}">Bewerken</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <h6 class="mb-1 mt-3">{{ $movie->title }}</h6>
                <p class="mb-3 text-muted">{{ $movie->tagline }}</p>
                <h6 class="mb-1 mt-3">Overview English</h6>
                <p class="mb-1 mt-3">{{ $movie->overview_en }}</p>
                @if (isset($movie->overview_nl))
                    <h6 class="mb-1 mt-3">Overview Dutch</h6>
                    <p class="mb-0">{{ $movie->overview_nl }}</p>
                @endif
                <h6 class="mb-1 mt-3">Genres</h6>
                <p class="mb-3 text-muted">
                    <ul>
                        @foreach($movie->genres as $genre)
                            <li>{{ $genre->genre }}</li>
                        @endforeach
                    </ul>
                </p>
            </div>
            <hr class="wid-80 b-wid-3 my-4">
            <div class="row text-center">
                <div class="col">
                    <h6 class="mb-1"><a href="{{ $movie->homepage }}" rel="nofollow" target="_blank">Website</a></h6>
                    <p class="mb-0">Homepage</p>
                </div>
                <div class="col">
                    <h6 class="mb-1">2749</h6>
                    <p class="mb-0">Artikelen</p>
                </div>
                <div class="col">
                    <h6 class="mb-1"><a href="{{ $movie->trailer }}" rel="nofollow" target="_blank">YouTube</a></h6>
                    <p class="mb-0">Trailer</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection