routes/web.php
<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['as' => 'admin.', 'name' => 'admin.', 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::resource('article', 'ArticleController');
    Route::resource('movie', 'MovieController');
    Route::resource('show', 'ShowController');
    Route::resource('type', 'TypeController');
    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/TypeController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreTypeRequest;
use App\Http\Requests\UpdateTypeRequest;
use App\Type;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

final class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $view = view('admin.type.index');
        $view->types = Type::latest()->take(50)->get();

        return $view;
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        return view('admin.type.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreTypeRequest $request): RedirectResponse
    {
        $title = $request->get('title');

        $type = Type::create([
            'title' => $title,
            'is_active' => 1,
        ]);

        return redirect()->action(
            'Admin\TypeController@show',
            ['type' => $type]
        );
    }

    /**
     * Display the specified resource.
     */
    public function show(Type $type): View
    {
        $view = view('admin.type.show');
        $view->type = $type;

        return $view;
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Type $type): View
    {
        $view = view('admin.type.edit');
        $view->type = $type;

        return $view;
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateTypeRequest $request, Type $type): RedirectResponse
    {
        $active = $request->get('is_active') !== null && $request->get('is_active') === 1 ? true : false;

        $type->title = $request->get('title');
        $type->is_active = $active;

        $type->save();

        return redirect()->action(
            'Admin\TypeController@show',
            ['type' => $type]
        );
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Type $type): RedirectResponse
    {
        $type->delete();

        return redirect()->action(
            'Admin\TypeController@index',
        );
    }

    /**
     * @return array[]
     */
    public function search(Request $request): array
    {
        $search = $request->query('s');

        $types = Type::where(['title' => $search, 'is_active' => true])->take(10)->get();

        $result = [];

        foreach ($types as $type) {
            $result[] = [
                'title' => $type->title,
            ];
        }

        return ['data' => $result];
    }
}

resources/views/admin/type/create.blade.php
@extends('admin.base')

@section('content')
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h5>Toevoegen type</h5>
            </div>
            <div class="card-body">
                {!! Form::open(['route' => ['admin.type.store'], 'method' => 'POST', 'id' => 'sa-new-article']) !!}
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group row">
                                <div class="col-sm-12">
                                    {!! Form::text('title', null, ['id' => 'articleTitle', 'class' => 'form-control', 'placeholder' => 'Naam van het type']) !!}
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-12">
                                    {!! Form::submit('Opslaan', ['class' => 'btn btn-primary']) !!}
                                </div>
                            </div>
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

@section('extra-css')
    <link rel="stylesheet" href="/vendor/backend/css/style.css">
@endsection

@section('extra-js')

@endsection

resources/views/admin/type/edit.blade.php
@extends('admin.base')

@section('content')
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h5>Bewerken categorie</h5><small>{{ $type->title }}</small>
            </div>
            {{ Form::open(['action' => ['Admin\TypeController@update', $type->id], 'method' => 'PATCH']) }}
            <div class="col-12">
                <div class="form-group row m-t-20">
                    <label for="categoryTitle" class="col-1 col-form-label">Naam</label>
                    <div class="col-11">
                        {!! Form::text('title', $type->title, ['id' => 'categoryTitle', 'class' => 'form-control', 'placeholder' => 'Naam van het artikel']) !!}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-1 col-form-label">Actief?</label>
                    <div class="col-11">
                        Nee
                        <div class="col-10 switch switch-success d-inline m-r-10">
                            <input name="is_active" value="1" type="checkbox" id="switch-s-1" @if ($type->is_active) checked @endif>
                            <label for="switch-s-1" class="cr"></label>
                        </div>
                        Ja
                    </div>
                </div>
                @if ($errors->any())
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                @endif
                <div class="form-group row">
                    <div class="offset-1 col-11">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Reset</button>
                        <a class="btn btn-warning" href="{{ route('admin.type.index') }}">Annuleren</a>
                        <button type="submit" class="btn btn-success">Opslaan</button>
                    </div>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('extra-css')

@endsection

@section('extra-js')


@endsection

resources/views/admin/type/index.blade.php
@extends('admin.base')
@section('content')
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h5>Typen</h5>
                <hr>
                <table id="footable-table" class="table table-striped table-hover footable footable-1 footable-paging footable-paging-center breakpoint-lg" style="">
                    <thead>
                    <tr class="footable-header">
                        <th class="footable-sortable footable-first-visible" >
                            Type
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th class="footable-sortable footable-first-visible" >
                            Actief?
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th class="footable-sortable footable-first-visible" >
                            # Artikelen
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th data-breakpoints="xs" class="footable-sortable" >
                            Aangemaakt op
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th class="footable-last-visible">
                            Opties
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($types as $type)
                        <tr>
                            <td><a href="{{ route('admin.category.show', $type) }}">{{ $type->title }}</a></td>
                            <td>@if ($type->is_active) Ja @else Nee @endif </td>
                            <td>
                                {{ $type->articles->count() }}
                            </td>
                            <td>
                                {{ $type->created_at->format('d-m-Y H:i') }}
                            </td>
                            <td>
                                <a href="{{ route('admin.type.edit', $type) }}" class="btn btn-primary">Bewerken</a>
                                <a href="{{ route('admin.type.destroy', $type->id) }}" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-type="{{ $type->title }}">Verwijder</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel">Verwijderen categorie</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            </div>
                            <div class="modal-body">
                                Weet je zeker dat je deze categorie wilt verwijderen?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary">Annuleren</button>
                                {{ Form::open(['method' => 'DELETE', 'id' => 'deleteCategoryForm']) }}
                                <button type="submit" class="btn btn-danger">Verwijderen</button>
                                {{ Form::close() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('extra-css')
    <!-- datatables css -->
    <link rel="stylesheet" href="/vendor/backend/plugins/data-tables/css/datatables.min.css">

    <!-- footable css -->
    <link rel="stylesheet" href="/vendor/backend/plugins/footable/css/footable.bootstrap.min.css">
    <link rel="stylesheet" href="/vendor/backend/plugins/footable/css/footable.standalone.min.css">
@endsection

@section('extra-js')
    <script src="/vendor/backend/plugins/footable/js/footable.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#footable-table').footable({
                "paging": {
                    "enabled": false,
                    "size": 50
                },
                "sorting": {
                    "enabled": true
                }
            });
        });

        $('#deleteModal').on('show.bs.modal', function(e) {
            let button = $(e.relatedTarget);
            let type = button.data('type');
            let modal = $(this);

            modal.find('.modal-title').text('Verwijderen type ' + type);
            modal.find('.modal-body').text('Weet je zeker dat je het type ' + type + ' wilt verwijderen?');
            modal.find('#deleteCategoryForm').attr('action', button.attr('href'));
        })
    </script>
@endsection

resources/views/admin/type/show.blade.php
@extends('admin.base')
@section('content')
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h5>Bekijk type "{{$type->title}}"</h5>
                <hr>
                <h6>Artikelen bij dit type</h6>
                <table id="footable-table" class="table table-striped table-hover footable footable-1 footable-paging footable-paging-center breakpoint-lg" style="">
                    <thead>
                    <tr class="footable-header">
                        <th class="footable-sortable footable-first-visible" >
                            Titel
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th data-breakpoints="xs" class="footable-sortable" >
                            Gepubliceerd (op)
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th data-breakpoints="xs" class="footable-sortable" >
                            Categorien
                            <span class="fooicon fooicon-sort"></span>
                        </th>
                        <th class="footable-last-visible">
                            Opties
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($type->articles as $article)
                        <tr>
                            <td><a href="{{ route('admin.article.show', $article) }}">{{ $article->title }}</a></td>
                            <td>
                                @if ($article->published)
                                    Ja
                                @else
                                    Nee
                                @endif
                                ({{ $article->published_at->format('Y-m-d H:i') }})
                            </td>
                            <td>
                                <ul>
                                    @foreach($article->categories as $category)
                                        <li>{{$category->category }}</li>
                                    @endforeach
                                </ul>
                            </td>
                            <td>
                                <a href="{{ route('admin.article.show', $article) }}">Bekijken</a>
                                <a href="{{ route('admin.article.edit', $article) }}">Bewerken</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection